# permissions for end users to edit upfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: upf-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nephio-5gc-controller
    app.kubernetes.io/part-of: nephio-5gc-controller
    app.kubernetes.io/managed-by: kustomize
  name: upf-editor-role
rules:
- apiGroups:
  - nf.nephio.org
  resources:
  - upfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nf.nephio.org
  resources:
  - upfs/status
  verbs:
  - get
